apiVersion: v1
kind: Pod
metadata:
  labels:
    run: build-observer
  name: build-observer
spec:
  serviceAccountName: build-robot
  containers:
  - image: alpine
    name: build-observer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
