kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: exercise-25
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
