apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-backup
  namespace: exercise-21
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: busybox:1.37
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - "date; echo Backup successful"
          restartPolicy: OnFailure

