apiVersion: v1
kind: Pod
metadata:
  namespace: exercise-22
  name: background-job
spec:
  containers:
  - name: background-app
    image: busybox:1.37
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "sleep 3600"]
  priorityClassName: low-priority
