apiVersion: v1
kind: Pod
metadata:
  namespace: exercise-22
  name: critical-app
spec:
  containers:
  - name: critical-app
    image: nginx:1.28
    imagePullPolicy: IfNotPresent
  priorityClassName: high-priority
