apiVersion: v1
kind: Pod
metadata:
  labels:
    app: db-mock
  name: db-mock
  namespace: finance-prod
spec:
  containers:
  - image: postgres:15-alpine
    name: db-mock
    env:
      - name: POSTGRES_PASSWORD
        value: supersecret
    ports:
     - containerPort: 5432
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
