apiVersion: v1
kind: Namespace
metadata:
  name: finance-prod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: finance-quota
  namespace: finance-prod
spec:
  hard:
    pods: "5"
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1000m"
    limits.memory: "1024Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor-sa
  namespace: finance-prod
