apiVersion: v1
kind: Pod
metadata:
  labels:
    run: storage-consumer
  name: storage-consumer
  namespace: exercise-12
spec:
  volumes:
    - name: data 
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - image: busybox:1.35
      name: storage-consumer
      resources: {}
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
