apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv 
  namespace: exercise-12
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/exercise-12"
