apiVersion: v1
kind: Pod
metadata:
  labels:
    run: norogue
  name: norogue
  namespace: exercise-20
spec:
  securityContext:
    runAsUser: 10000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: nginx:1.28
    name: rogue
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
